AlizeeDriget/Map_the_Maker

app/assets/stylesheets/application.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/config/_fonts.scss, app/views/pages/home.html.erb
=> css config done

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_index.scss, app/views/pages/home.html.erb
=> 22 create button class

Gemfile, Gemfile.lock, app/models/maker.rb, config/environments/development.rb, config/environments/production.rb, config/storage.yml, db/migrate/20250610094847_create_active_storage_tables.active_storage.rb, db/schema.rb
@jannisbraun -> I am doing a pull request
=> Le Wagon Day 37 Cloudinary Hosting

app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_makers_show.scss, app/views/makers/show.html.erb
This is my push from yesterday - I'll be pulling it before starting - so it's structurally similiar to what it will look like by the end of the day.
=> added makers show changes

app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_makers_index.scss, app/assets/stylesheets/pages/_makers_search.scss, app/controllers/makers_controller.rb, app/controllers/pages_controller.rb, app/views/makers/index.html.erb, app/views/shared/_star_rating_overall.html.erb
=> 1 makers index

app/assets/stylesheets/pages/_makers_index.scss, app/views/makers/index.html.erb
=> 49 search bar adjustments

app/controllers/makers_controller.rb, app/views/makers/show.html.erb, app/views/shared/_star_rating_accuracy.html.erb, app/views/shared/_star_rating_freshness.html.erb, app/views/shared/_star_rating_overall.html.erb, app/views/shared/_star_rating_product_range.html.erb, app/views/shared/_star_rating_service.html.erb
Could you please review my code @jannisbraun  - for the stars logic!
=> Map the Maker Updated Stars

Gemfile, Gemfile.lock, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_questions.scss, app/controllers/questions_controller.rb, app/controllers/users_controller.rb, app/models/question.rb, app/models/user.rb, app/views/questions/_form.html.erb, app/views/questions/_question.html.erb, app/views/questions/index.html.erb, bin/jobs, config/application.rb, config/cable.yml, config/environments/production.rb, config/puma.rb, config/queue.yml, config/recurring.yml, config/routes.rb, db/migrate/20250616020049_create_solid_cable_message.solid_cable.rb, db/migrate/20250616020050_index_channels.solid_cable.rb, db/migrate/20250616020555_install_solid_queue.rb, db/migrate/20250616021527_create_questions.rb, db/schema.rb, test/controllers/messages_controller_test.rb, test/controllers/questions_controller_test.rb, test/models/question_test.rb
=> 14_version without AI

app/controllers/makers_controller.rb
=> adjusted login requirements

app/assets/stylesheets/pages/_makers_index.scss, app/assets/stylesheets/pages/_makers_search.scss, app/views/makers/_search_bar.html.erb, app/views/makers/index.html.erb
=> index improvements

app/services/chatbot_service.rb
=> improved chatbot

app/assets/stylesheets/components/_questions.scss, app/views/makers/_homebar.html.erb, app/views/questions/index.html.erb
closed #66 
more basic styling
=> more basic chat improvements

app/assets/stylesheets/components/_homebar.scss, app/views/karma/dashboard.html.erb, app/views/makers/_homebar.html.erb, app/views/makers/index.html.erb, app/views/makers/map.html.erb
=> improved bottom bar

app/assets/stylesheets/pages/_makers_show.scss, app/views/makers/show.html.erb
@jannisbraun - shouldn't be any major* conflicts
=> Substantial changes to show page

app/controllers/makers_controller.rb
woudl you reveiw my conflicts...
=> Fixed the rerouting to index in all cirucmstnaces issue

app/assets/stylesheets/pages/_makers_index.scss, app/views/layouts/application.html.erb, app/views/makers/index.html.erb, app/views/makers/map.html.erb, app/views/questions/index.html.erb, app/views/shared/_homebar.html.erb
=> added and adjusted homebar

app/assets/stylesheets/pages/_makers_index.scss, app/views/makers/index.html.erb
=> improved index page

app/assets/stylesheets/pages/_home.scss, app/views/makers/_info_window.html.erb, app/views/pages/_hero_section.html.erb, app/views/pages/_how_it_works_section.html.erb, app/views/pages/_popular_producers_section.html.erb, app/views/pages/_why_it_matters.html.erb
Reverts AlizeeDriget/Map_the_Maker#144
=> Revert "97 home page"

app/views/shared/_homebar.html.erb
=> params transfer added

app/assets/stylesheets/pages/_makers_index.scss
=> Favourite icon changed 

app/assets/stylesheets/components/_map.scss, app/controllers/makers_controller.rb, app/javascript/controllers/map_controller.js, app/views/makers/map.html.erb, db/seeds.rb
=> 125 map direction feature

db/seeds.rb
=> changed seed locations

app/assets/stylesheets/pages/_users_new.scss, app/javascript/controllers/favorite_controller.js, app/models/maker.rb, app/models/review.rb, app/views/makers/new.html.erb, app/views/makers/show.html.erb, app/views/reviews/_new_form.html.erb, app/views/users/favorites.html.erb
=> favaorite problem
